

/*  This explains named vs default export --- https://bobbyhadz.com/blog/javascript-export-class#:~:text=Use%20named%20exports%20to%20export,as%20necessary%20in%20a%20file.
*/


// This class contains common resourcres 
export default class Resources {

    constructor() {
    }
    // countrylist with all countries 
    static DistrictSimplifiedCriteria = [
        '	Projects should be short-term with the expectation of completion within the year the grant is received.',
        '	Priority will be given to local community projects and to International projects that are ineligible for TRF Matching Grants.',
        '	Participating clubs must be certified for the year in which the grant is requested',
        '	The project supported by this grant must respect the wishes, traditions and culture of the receiving community.',
        '	The project must promote the active and personal participation of Rotarians from all clubs involved in its implementation.',
        '	Project funds must not directly benefit a Rotarian, his/her spouse, a living Rotarian’s lineal descendant or ancestor or his/her spouse or an employee of a club, district or other Rotary entity or of Rotary International.',
        '	Project funds may not be used for salaries, travel or administrative overhead costs.',
        '	Project funds may not be used to reimburse applicants for projects already initiated or completed.',
        '	Project funds may not be used to purchase land or construct substantial buildings.',
        '	Project funds may not be used to fund a Rotary club’s on-going projects, but may be used to replicate successful projects that will benefit additional communities.',
        '	Projects must be sponsored by a Rotary club and/or district and publicly identified as such.',
        '	The stewardship of the DSG grant funds shall conform to the District Memorandum of Understanding.',
        '	The sponsor club shall appoint two Rotarians who will provide oversight and management of the project funds and who will serve as contacts for the District 7040 Rotary Foundation Committee.',
        '	Projects must adhere to Rotary’s seven areas of focus'
    ]
    static countryList = [
        'Afghanistan',
        'Albania',
        'Algeria',
        'American Samoa',
        'Andorra',
        'Angola',
        'Anguilla',
        'Antarctica',
        'Antigua and Barbuda',
        'Argentina',
        'Armenia',
        'Aruba',
        'Australia',
        'Austria',
        'Azerbaijan',
        'Bahamas (the)',
        'Bahrain',
        'Bangladesh',
        'Barbados',
        'Belarus',
        'Belgium',
        'Belize',
        'Benin',
        'Bermuda',
        'Bhutan',
        'Bolivia (Plurinational State of)',
        'Bonaire, Sint Eustatius and Saba',
        'Bosnia and Herzegovina',
        'Botswana',
        'Bouvet Island',
        'Brazil',
        'British Indian Ocean Territory (the)',
        'Brunei Darussalam',
        'Bulgaria',
        'Burkina Faso',
        'Burundi',
        'Cabo Verde',
        'Cambodia',
        'Cameroon',
        'Canada',
        'Cayman Islands (the)',
        'Central African Republic (the)',
        'Chad',
        'Chile',
        'China',
        'Christmas Island',
        'Cocos (Keeling) Islands (the)',
        'Colombia',
        'Comoros (the)',
        'Congo (the Democratic Republic of the)',
        'Congo (the)',
        'Cook Islands (the)',
        'Costa Rica',
        'Croatia',
        'Cuba',
        'Curaçao',
        'Cyprus',
        'Czechia',
        "Côte d'Ivoire",
        'Denmark',
        'Djibouti',
        'Dominica',
        'Dominican Republic (the)',
        'Ecuador',
        'Egypt',
        'El Salvador',
        'Equatorial Guinea',
        'Eritrea',
        'Estonia',
        'Eswatini',
        'Ethiopia',
        'Falkland Islands (the) [Malvinas]',
        'Faroe Islands (the)',
        'Fiji',
        'Finland',
        'France',
        'French Guiana',
        'French Polynesia',
        'French Southern Territories (the)',
        'Gabon',
        'Gambia (the)',
        'Georgia',
        'Germany',
        'Ghana',
        'Gibraltar',
        'Greece',
        'Greenland',
        'Grenada',
        'Guadeloupe',
        'Guam',
        'Guatemala',
        'Guernsey',
        'Guinea',
        'Guinea-Bissau',
        'Guyana',
        'Haiti',
        'Heard Island and McDonald Islands',
        'Holy See (the)',
        'Honduras',
        'Hong Kong',
        'Hungary',
        'Iceland',
        'India',
        'Indonesia',
        'Iran (Islamic Republic of)',
        'Iraq',
        'Ireland',
        'Isle of Man',
        'Israel',
        'Italy',
        'Jamaica',
        'Japan',
        'Jersey',
        'Jordan',
        'Kazakhstan',
        'Kenya',
        'Kiribati',
        "Korea (the Democratic People's Republic of)",
        'Korea (the Republic of)',
        'Kuwait',
        'Kyrgyzstan',
        "Lao People's Democratic Republic (the)",
        'Latvia',
        'Lebanon',
        'Lesotho',
        'Liberia',
        'Libya',
        'Liechtenstein',
        'Lithuania',
        'Luxembourg',
        'Macao',
        'Madagascar',
        'Malawi',
        'Malaysia',
        'Maldives',
        'Mali',
        'Malta',
        'Marshall Islands (the)',
        'Martinique',
        'Mauritania',
        'Mauritius',
        'Mayotte',
        'Mexico',
        'Micronesia (Federated States of)',
        'Moldova (the Republic of)',
        'Monaco',
        'Mongolia',
        'Montenegro',
        'Montserrat',
        'Morocco',
        'Mozambique',
        'Myanmar',
        'Namibia',
        'Nauru',
        'Nepal',
        'Netherlands (the)',
        'New Caledonia',
        'New Zealand',
        'Nicaragua',
        'Niger (the)',
        'Nigeria',
        'Niue',
        'Norfolk Island',
        'Northern Mariana Islands (the)',
        'Norway',
        'Oman',
        'Pakistan',
        'Palau',
        'Palestine, State of',
        'Panama',
        'Papua New Guinea',
        'Paraguay',
        'Peru',
        'Philippines (the)',
        'Pitcairn',
        'Poland',
        'Portugal',
        'Puerto Rico',
        'Qatar',
        'Republic of North Macedonia',
        'Romania',
        'Russian Federation (the)',
        'Rwanda',
        'Réunion',
        'Saint Barthélemy',
        'Saint Helena, Ascension and Tristan da Cunha',
        'Saint Kitts and Nevis',
        'Saint Lucia',
        'Saint Martin (French part)',
        'Saint Pierre and Miquelon',
        'Saint Vincent and the Grenadines',
        'Samoa',
        'San Marino',
        'Sao Tome and Principe',
        'Saudi Arabia',
        'Senegal',
        'Serbia',
        'Seychelles',
        'Sierra Leone',
        'Singapore',
        'Sint Maarten (Dutch part)',
        'Slovakia',
        'Slovenia',
        'Solomon Islands',
        'Somalia',
        'South Africa',
        'South Georgia and the South Sandwich Islands',
        'South Sudan',
        'Spain',
        'Sri Lanka',
        'Sudan (the)',
        'Suriname',
        'Svalbard and Jan Mayen',
        'Sweden',
        'Switzerland',
        'Syrian Arab Republic',
        'Taiwan',
        'Tajikistan',
        'Tanzania, United Republic of',
        'Thailand',
        'Timor-Leste',
        'Togo',
        'Tokelau',
        'Tonga',
        'Trinidad and Tobago',
        'Tunisia',
        'Turkey',
        'Turkmenistan',
        'Turks and Caicos Islands (the)',
        'Tuvalu',
        'Uganda',
        'Ukraine',
        'United Arab Emirates (the)',
        'United Kingdom of Great Britain and Northern Ireland (the)',
        'United States Minor Outlying Islands (the)',
        'United States of America (the)',
        'Uruguay',
        'Uzbekistan',
        'Vanuatu',
        'Venezuela (Bolivarian Republic of)',
        'Viet Nam',
        'Virgin Islands (British)',
        'Virgin Islands (U.S.)',
        'Wallis and Futuna',
        'Western Sahara',
        'Yemen',
        'Zambia',
        'Zimbabwe',
        'Åland Islands',
    ]
    // generic DSG project 
    static genericProject = {
        area_focus: '',
        project_name: '',
        project_theme: '',
        country: '',
        grant_type: 1,
        estimated_completion: '',
        funding_goal: 0,
        current_funds: 0,
        anticipated_funding: 0,
        created_by: 0,
        region: '',
        rotary_year: 2022,
        image_link: '',

        district_id: 0,
        club_id: 0,

        extra_descriptions: [],
        itemised_budget: [],
        attached_letters: [],
        project_funding: [],
        hostclub_information: [],

        role_type: 1,
    }
    // region list 
    static regionList = [
        'Africa',
        'Central America',
        'North America',
        'South America',
        'Asia',
        'South East Asia',
        'Eastern Europe',
        'Western Europe',
        'Middle East',
    ]
    // areaOfFocus list 
    static areaOfFocus = [
        'Peace Conflict Prevention',
        'Disease Prevention And Treatment',
        'Water And Sanitation',
        'Maternal And Child Health',
        'Basic Education And Literacy',
        'Economic And Community Development',
        'Environment',
    ]
    // status list 

    static statusList = [
        'Looking for funding',
        'Fully funded',
        'Pending approval',
        'Approved',
        'Completed',
    ]

    static searchTermConversionMap() {
        const searchTermConversionMap = new Map();
        searchTermConversionMap.set('Peace Conflict Prevention', 'Peace_Conflict_Prevention');
        searchTermConversionMap.set('Disease Prevention And Treatment', 'Disease_Prevention_And_Treatment');
        searchTermConversionMap.set('Water And Sanitation', 'Water_And_Sanitation');
        searchTermConversionMap.set('Maternal And Child Health', 'Maternal_And_Child_Health');
        searchTermConversionMap.set('Basic Education And Literacy', 'Basic_Education_And_Literacy');
        searchTermConversionMap.set('Economic And Community Development', 'Economic_And_Community_Development');
        searchTermConversionMap.set('Environment', 'Environment');
        return searchTermConversionMap
    }

    static reverseTermConversionMap() {
        const searchTermConversionMap = new Map();
        searchTermConversionMap.set( 'Peace_Conflict_Prevention','Peace Conflict Prevention');
        searchTermConversionMap.set( 'Disease_Prevention_And_Treatment','Disease Prevention And Treatment');
        searchTermConversionMap.set( 'Water_And_Sanitation','Water And Sanitation');
        searchTermConversionMap.set( 'Maternal_And_Child_Health','Maternal And Child Health');
        searchTermConversionMap.set( 'Basic_Education_And_Literacy','Basic Education And Literacy');
        searchTermConversionMap.set( 'Economic_And_Community_Development','Economic And Community Development');
        searchTermConversionMap.set('Environment', 'Environment');
        return searchTermConversionMap
    }
}