enum AreaFocus {
  PEACE_CONFLICT_PREVENTION = 1,
  DISEASE_PREVENTION_AND_TREATMENT = 2,
  WATER_AND_SANITATION = 3,
  MATERNAL_AND_CHILD_HEALTH = 4,
  BASIC_EDUCATION_AND_LITERACY = 5,
  ECONOMIC_AND_COMMUNITY_DEVELOPMENT = 6,
  ENVIRONMENT = 7,
}

export default AreaFocus
