enum RoleType {
  DISTRICT_ADMIN = 1,
  DISTRICT_GRANTS_CHAIR = 2,
  DISTRICT_FOUNDATIONS_CHAIR = 3,
  DISTRICT_INTERNATIONAL_CHAIR = 4,
  CLUB_ADMIN = 5,
  TITLED_MEMBER = 6,
  STANDARD_MEMBER = 7,
}

export default RoleType
