enum RoleType {
  DISTRICT_ADMIN = 1,
  DISTRICT_GRANTS_CHAIR,
  DISTRICT_FOUNDATIONS_CHAIR,
  DISTRICT_INTERNATIONAL_CHAIR,
  CLUB_ADMIN,
  TITLED_MEMBER,
  STANDARD_MEMBER,
}

export default RoleType
